dist: trusty
sudo: false
language: php
php: 7.2

addons:
  sonarcloud:
    organization: "guillemcanal-github"

install: composer install

script: 
  - vendor/bin/phpunit --testdox --log-junit build/phpunit.xml --coverage-clover build/phpunit.coverage.xml --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/phpunit.coverage.xml
  - sonar-scanner
